In [15]:
import pandas as pd
from matplotlib import pyplot as plt
import altair as alt
import seaborn as sns
import numpy as np

In [16]:
uk_covid_data = pd.read_excel("lahbtablesweek01to5320201.xlsx", sheet_name='Registrations - All data', skiprows=3)

In [17]:
uk_covid_data = uk_covid_data[uk_covid_data['Cause of death']=='COVID 19']
uk_covid_data.head()

,Area code,Geography type,Area name,Cause of death,Week number,Place of death,Number of deaths
6,E06000001,Local Authority,Hartlepool,COVID 19,1,Care home,0
7,E06000001,Local Authority,Hartlepool,COVID 19,1,Elsewhere,0
8,E06000001,Local Authority,Hartlepool,COVID 19,1,Home,0
9,E06000001,Local Authority,Hartlepool,COVID 19,1,Hospice,0
10,E06000001,Local Authority,Hartlepool,COVID 19,1,Hospital,0

In [18]:
london_covid = uk_covid_data[uk_covid_data['Area code'].str.contains('E09')]
london_covid.head()

,Area code,Geography type,Area name,Cause of death,Week number,Place of death,Number of deaths
3378,E09000001,Local Authority,City of London,COVID 19,1,Care home,0
3379,E09000001,Local Authority,City of London,COVID 19,1,Elsewhere,0
3380,E09000001,Local Authority,City of London,COVID 19,1,Home,0
3381,E09000001,Local Authority,City of London,COVID 19,1,Hospice,0
3382,E09000001,Local Authority,City of London,COVID 19,1,Hospital,0

In [20]:
london_covid_agg = london_covid.groupby(['Area code', 'Area name ', 'Week number']).sum().reset_index()
london_covid_agg.rename(columns = {'Area code':'code'}, inplace = True)
london_covid_agg.rename(columns = {'Area name ':'name'}, inplace = True)
london_covid_agg.rename(columns = {'Week number':'week'}, inplace = True)
london_covid_agg.rename(columns = {'Number of deaths':'count'}, inplace = True)

london_covid_agg.head()

        code            name  week  count
0  E09000001  City of London     1      0
1  E09000001  City of London     2      0
2  E09000001  City of London     3      0
3  E09000001  City of London     4      0
4  E09000001  City of London     5      0

In [22]:
import altair as alt
alt.data_transformers.disable_max_rows()

alt.Chart(london_covid_agg).mark_line().encode(
    x='week:O',
    y='count',
    color='name',
    tooltip=['name','count']
).properties(
    width=800,
    height=500
)

alt.Chart(...)

In [27]:
# now lets get income and other data
uk_deprivation_data = pd.read_excel("File_2_-_IoD2019_Domains_of_Deprivation.xlsx", sheet_name='IoD2019 Domains')

In [29]:
london_deprivation = uk_deprivation_data[uk_deprivation_data['Local Authority District code (2019)'].str.contains('E09')]
london_deprivation.head()

,LSOA code (2011),LSOA name (2011),Local Authority District code (2019),Local Authority District name (2019),Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Employment Rank (where 1 is most deprived),Employment Decile (where 1 is most deprived 10% of LSOAs),"Education, Skills and Training Rank (where 1 is most deprived)","Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)",Health Deprivation and Disability Rank (where 1 is most deprived),Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs),Crime Rank (where 1 is most deprived),Crime Decile (where 1 is most deprived 10% of LSOAs),Barriers to Housing and Services Rank (where 1 is most deprived),Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs),Living Environment Rank (where 1 is most deprived),Living Environment Decile (where 1 is most deprived 10% of LSOAs)
0,E01000001,City of London 001A,E09000001,City of London,29199,9,32831,10,32742,10,32842,10,32113,10,32662,10,7319,3,7789,3
1,E01000002,City of London 001B,E09000001,City of London,30379,10,29901,10,31190,10,32832,10,29705,10,32789,10,11707,4,13070,4
2,E01000003,City of London 001C,E09000001,City of London,14915,5,18510,6,15103,5,26386,9,17600,6,29363,9,2157,1,4092,2
3,E01000005,City of London 001E,E09000001,City of London,8678,3,6029,2,7833,3,12370,4,17907,6,31059,10,2217,1,9397,3
4,E01000006,Barking and Dagenham 016A,E09000002,Barking and Dagenham,14486,5,14023,5,21692,7,17511,6,21581,7,18848,6,1033,1,10629,4

In [36]:
london_deprivation_agg = london_deprivation.groupby(['Local Authority District code (2019)', 'Local Authority District name (2019)']).median().reset_index()
london_deprivation_agg.rename(columns = {'Local Authority District code (2019)':'code'}, inplace = True)
london_deprivation_agg.rename(columns = {'Local Authority District name (2019)':'name'}, inplace = True)
london_deprivation_agg.rename(columns = {'Income Rank (where 1 is most deprived)':'income_rank'}, inplace = True)
london_deprivation_agg.rename(columns = {'Employment Rank (where 1 is most deprived)':'employment_rank'}, inplace = True)
london_deprivation_agg.rename(columns = {'Education, Skills and Training Rank (where 1 is most deprived)':'education_rank'}, inplace = True)
london_deprivation_agg.rename(columns = {'Health Deprivation and Disability Rank (where 1 is most deprived)':'health_rank'}, inplace = True)
london_deprivation_agg.rename(columns = {'Living Environment Rank (where 1 is most deprived)':'living_env_rank'}, inplace = True)

london_deprivation_agg = london_deprivation_agg[['code', 'name', 'income_rank', 
                                                 'employment_rank', 'education_rank',
                                                'health_rank', 'living_env_rank']]

london_deprivation_agg.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5
1,E09000002,Barking and Dagenham,6888.5,9387.0,10212.5,12807.0,9698.0
2,E09000003,Barnet,17032.0,20563.0,27297.0,29450.0,13192.0
3,E09000004,Bexley,18572.0,21212.5,15888.0,25579.5,16200.0
4,E09000005,Brent,11786.0,15204.0,18687.0,23514.0,10075.0

In [175]:
london_combined = pd.merge(london_deprivation_agg, london_covid_agg, left_on='code', right_on='code', how = 'inner')
london_combined.drop(['name_y'], axis=1, inplace=True)
london_combined.rename(columns = {'name_x':'name'}, inplace = True)
london_combined.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank,week,count
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,1,0
1,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,2,0
2,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,3,0
3,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,4,0
4,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,5,0

In [176]:
london_combined_agg = london_combined.groupby(['code', 
                                               'name',
                                               'income_rank',
                                               'employment_rank',
                                               'education_rank',
                                               'health_rank',
                                               'living_env_rank']).sum().reset_index()

london_combined_agg.rename(columns = {'count':'covid_deaths'}, inplace = True)
london_combined_agg.drop(['week'], axis=1, inplace=True)

london_combined_agg.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank,covid_deaths
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,6
1,E09000002,Barking and Dagenham,6888.5,9387.0,10212.5,12807.0,9698.0,295
2,E09000003,Barnet,17032.0,20563.0,27297.0,29450.0,13192.0,560
3,E09000004,Bexley,18572.0,21212.5,15888.0,25579.5,16200.0,339
4,E09000005,Brent,11786.0,15204.0,18687.0,23514.0,10075.0,556

In [177]:
# now load and transform population estimates - I want london age 61-70, 71-80, 80_plus
# I also want to divide the covid deaths by the borough population to pro rata it, but also
# multiply by 100,000 to get a big number

# skip first four rows as just header information text
uk_by_age = pd.read_excel("ukmidyearestimates20192020ladcodes.xls", sheet_name='MYE2 - Males', skiprows=4)

uk_by_age = uk_by_age.dropna(how='all') # only drops a row when every column is NA

# Now check for NaN values
nan_values = uk_by_age[uk_by_age.isna().any(axis=1)]
print(nan_values)

# Row 427 is just description data so remove it
nan_values_index = uk_by_age[uk_by_age.isna().any(axis=1)].index
uk_by_age = uk_by_age.drop(nan_values_index)

london_by_age = uk_by_age[uk_by_age['Code'].str.contains('E09')]
london_by_age.head()

# I want to melt the data because the ages 0-90+ are in columns and I want them in rows - tidy data
col_names = london_by_age.columns.tolist()
col_names = col_names[4:95]

london_by_age = pd.melt(london_by_age, id_vars=['Code', 'Name', 'Geography1', 'All ages'], 
                        value_vars=col_names, var_name = 'Age', value_name='AgeTotal')

london_by_age.head()

                                                  Code Name Geography1  \
427  1. Further information, on how the different t...  NaN        NaN

     All ages   0   1   2   3   4   5  ...  81  82  83  84  85  86  87  88  \
427       NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN

     89  90+
427 NaN  NaN

[1 rows x 95 columns]

        Code                    Name      Geography1  All ages Age  AgeTotal
0  E09000007                  Camden  London Borough  135978.0   0    1310.0
1  E09000001          City of London  London Borough    5320.0   0      42.0
2  E09000012                 Hackney  London Borough  140023.0   0    2173.0
3  E09000013  Hammersmith and Fulham  London Borough   90740.0   0    1126.0
4  E09000014                Haringey  London Borough  135883.0   0    1785.0

In [178]:
london_by_age.loc[london_by_age.Age == '90+', "Age"] = 90 # need to convert from 90+ to 90 so we can then conv to numeric

# now get groupings for ages 60-69, 70-79, 80+
london_by_age['Age'] = pd.to_numeric(london_by_age['Age'])
london_by_age['AgeTotal'] = pd.to_numeric(london_by_age['AgeTotal'])

london_60s = london_by_age.groupby(["Code","Name", "All ages"]).apply(lambda x: x['AgeTotal'][(london_by_age.Age > 59) & (london_by_age.Age < 70)].sum()/x['All ages'].mean()).reset_index()
london_60s.rename(columns = {0:'60s_proportion'}, inplace = True)

london_70s = london_by_age.groupby(["Code","Name", "All ages"]).apply(lambda x: x['AgeTotal'][(london_by_age.Age > 69) & (london_by_age.Age < 80)].sum()/x['All ages'].mean()).reset_index()
london_70s.rename(columns = {0:'70s_proportion'}, inplace = True)

london_80s = london_by_age.groupby(["Code","Name", "All ages"]).apply(lambda x: x['AgeTotal'][london_by_age.Age > 79].sum()/x['All ages'].mean()).reset_index()
london_80s.rename(columns = {0:'80s_proportion'}, inplace = True)
    
london_by_age_agg = pd.merge(london_60s, london_70s, left_on='Code', right_on='Code', how = 'inner')
london_by_age_agg = pd.merge(london_by_age_agg, london_80s, left_on='Code', right_on='Code', how = 'inner')
    
# now drop duplicate fields and rename Name_x to Name
london_by_age_agg.drop(['Name_y'], axis=1, inplace=True)
london_by_age_agg.drop(['Name'], axis=1, inplace=True)
london_by_age_agg.drop(['All ages_y'], axis=1, inplace=True)
london_by_age_agg.drop(['All ages'], axis=1, inplace=True)
london_by_age_agg.rename(columns = {'Name_x':'Name'}, inplace = True)
london_by_age_agg.rename(columns = {'All ages_x':'all_ages'}, inplace = True)

london_by_age_agg.head()

,Code,Name,all_ages,60s_proportion,70s_proportion,80s_proportion
0,E09000001,City of London,5320.0,0.104699,0.068045,0.038722
1,E09000002,Barking and Dagenham,105877.0,0.065076,0.034720,0.019778
2,E09000003,Barnet,196542.0,0.084028,0.057616,0.034771
3,E09000004,Bexley,120082.0,0.094219,0.066121,0.040456
4,E09000005,Brent,168277.0,0.085015,0.047564,0.028138

In [179]:
# now merge with london_combined and then pro rata covid deaths
london_combined_agg = pd.merge(london_combined_agg, london_by_age_agg, left_on='code', right_on='Code', how = 'inner')
london_combined_agg.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank,covid_deaths,Code,Name,all_ages,60s_proportion,70s_proportion,80s_proportion
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,6,E09000001,City of London,5320.0,0.104699,0.068045,0.038722
1,E09000002,Barking and Dagenham,6888.5,9387.0,10212.5,12807.0,9698.0,295,E09000002,Barking and Dagenham,105877.0,0.065076,0.034720,0.019778
2,E09000003,Barnet,17032.0,20563.0,27297.0,29450.0,13192.0,560,E09000003,Barnet,196542.0,0.084028,0.057616,0.034771
3,E09000004,Bexley,18572.0,21212.5,15888.0,25579.5,16200.0,339,E09000004,Bexley,120082.0,0.094219,0.066121,0.040456
4,E09000005,Brent,11786.0,15204.0,18687.0,23514.0,10075.0,556,E09000005,Brent,168277.0,0.085015,0.047564,0.028138

In [180]:
london_combined_agg.drop(['Code'], axis=1, inplace=True)
london_combined_agg.drop(['Name'], axis=1, inplace=True)
london_combined_agg['covid_deaths'] = (london_combined_agg['covid_deaths'] * 100000)/london_combined_agg['all_ages']
london_combined_agg.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank,covid_deaths,all_ages,60s_proportion,70s_proportion,80s_proportion
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,112.781955,5320.0,0.104699,0.068045,0.038722
1,E09000002,Barking and Dagenham,6888.5,9387.0,10212.5,12807.0,9698.0,278.625197,105877.0,0.065076,0.034720,0.019778
2,E09000003,Barnet,17032.0,20563.0,27297.0,29450.0,13192.0,284.926377,196542.0,0.084028,0.057616,0.034771
3,E09000004,Bexley,18572.0,21212.5,15888.0,25579.5,16200.0,282.307090,120082.0,0.094219,0.066121,0.040456
4,E09000005,Brent,11786.0,15204.0,18687.0,23514.0,10075.0,330.407602,168277.0,0.085015,0.047564,0.028138

In [181]:
# I now want to get ethnicity - black and asian
# skip first four rows as just header information text
uk_ethnicity = pd.read_excel("ethnic-groups-by-borough.xls", sheet_name='2018', 
                             usecols = "A,B,C,D,E,F,G", names=['Code', 'Name', 'White', 
                                                             'Asian', 'Black', 'Mixed','Total'], 
                             skiprows=3)

uk_ethnicity = uk_ethnicity.dropna(how='all') # only drops a row when every column is NA

# Now check for NaN values
nan_values = uk_ethnicity[uk_ethnicity.isna().any(axis=1)]
#print(nan_values)

london_ethnicity = uk_ethnicity[uk_ethnicity['Code'].str.contains('E09')]

# The dropna drops data for City of London so just add back in and change - to 0 for black in Richmond

df = pd.DataFrame([['E09000001', 'City of London', 9000, 0, 0, 0, 9000]], columns=['Code', 'Name', 'White', 
                                                             'Asian', 'Black', 'Mixed','Total'])

london_ethnicity.loc[london_ethnicity.Code == 'E09000027', "Black"] = 0

london_ethnicity = london_ethnicity.append(df, ignore_index=True)
london_ethnicity.head()

C:\Users\phil\anaconda3\lib\site-packages\pandas\core\indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,Code,Name,White,Asian,Black,Mixed,Total
0,E09000002,Barking and Dagenham,109000.0,54000.0,36000,15000.0,215000.0
1,E09000003,Barnet,250000.0,57000.0,30000,54000.0,390000.0
2,E09000004,Bexley,195000.0,17000.0,21000,15000.0,248000.0
3,E09000005,Brent,102000.0,107000.0,62000,56000.0,328000.0
4,E09000006,Bromley,267000.0,15000.0,21000,28000.0,330000.0

In [182]:
# now merge with london_combined and then pro rata covid deaths
london_combined_agg = pd.merge(london_combined_agg, london_ethnicity, left_on='code', right_on='Code', how = 'inner')

london_combined_agg.drop(['Code'], axis=1, inplace=True)
london_combined_agg.drop(['Name'], axis=1, inplace=True)
london_combined_agg.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank,covid_deaths,all_ages,60s_proportion,70s_proportion,80s_proportion,White,Asian,Black,Mixed,Total
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,112.781955,5320.0,0.104699,0.068045,0.038722,9000.0,0.0,0,0.0,9000.0
1,E09000002,Barking and Dagenham,6888.5,9387.0,10212.5,12807.0,9698.0,278.625197,105877.0,0.065076,0.034720,0.019778,109000.0,54000.0,36000,15000.0,215000.0
2,E09000003,Barnet,17032.0,20563.0,27297.0,29450.0,13192.0,284.926377,196542.0,0.084028,0.057616,0.034771,250000.0,57000.0,30000,54000.0,390000.0
3,E09000004,Bexley,18572.0,21212.5,15888.0,25579.5,16200.0,282.307090,120082.0,0.094219,0.066121,0.040456,195000.0,17000.0,21000,15000.0,248000.0
4,E09000005,Brent,11786.0,15204.0,18687.0,23514.0,10075.0,330.407602,168277.0,0.085015,0.047564,0.028138,102000.0,107000.0,62000,56000.0,328000.0

In [183]:
london_combined_agg['White'] = pd.to_numeric(london_combined_agg['White'])
london_combined_agg['Asian'] = pd.to_numeric(london_combined_agg['Asian'])
london_combined_agg['Black'] = pd.to_numeric(london_combined_agg['Black'])
london_combined_agg['Mixed'] = pd.to_numeric(london_combined_agg['Mixed'])

london_combined_agg['White'] = london_combined_agg['White'] / london_combined_agg['all_ages']
london_combined_agg['Asian'] = london_combined_agg['Asian'] / london_combined_agg['all_ages']
london_combined_agg['Black'] = london_combined_agg['Black'] / london_combined_agg['all_ages']
london_combined_agg['Mixed'] = london_combined_agg['Mixed'] / london_combined_agg['all_ages']
london_combined_agg.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank,covid_deaths,all_ages,60s_proportion,70s_proportion,80s_proportion,White,Asian,Black,Mixed,Total
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,112.781955,5320.0,0.104699,0.068045,0.038722,1.691729,0.000000,0.000000,0.000000,9000.0
1,E09000002,Barking and Dagenham,6888.5,9387.0,10212.5,12807.0,9698.0,278.625197,105877.0,0.065076,0.034720,0.019778,1.029496,0.510026,0.340017,0.141674,215000.0
2,E09000003,Barnet,17032.0,20563.0,27297.0,29450.0,13192.0,284.926377,196542.0,0.084028,0.057616,0.034771,1.271993,0.290014,0.152639,0.274750,390000.0
3,E09000004,Bexley,18572.0,21212.5,15888.0,25579.5,16200.0,282.307090,120082.0,0.094219,0.066121,0.040456,1.623890,0.141570,0.174880,0.124915,248000.0
4,E09000005,Brent,11786.0,15204.0,18687.0,23514.0,10075.0,330.407602,168277.0,0.085015,0.047564,0.028138,0.606143,0.635856,0.368440,0.332785,328000.0

In [172]:
london_combined_agg.drop(['all_ages'], axis=1, inplace=True)
london_combined_agg.drop(['Total'], axis=1, inplace=True)
london_combined_agg.head()

,code,name,income_rank,employment_rank,education_rank,health_rank,living_env_rank,covid_deaths,60s_proportion,70s_proportion,80s_proportion,White,Asian,Black,Mixed
0,E09000001,City of London,30837.5,30316.5,30856.5,23587.0,5940.5,112.781955,0.104699,0.068045,0.038722,1691.729323,0.000000,0.000000,0.000000
1,E09000002,Barking and Dagenham,6888.5,9387.0,10212.5,12807.0,9698.0,278.625197,0.065076,0.034720,0.019778,1029.496491,510.025785,340.017190,141.673829
2,E09000003,Barnet,17032.0,20563.0,27297.0,29450.0,13192.0,284.926377,0.084028,0.057616,0.034771,1271.992755,290.014348,152.639131,274.750435
3,E09000004,Bexley,18572.0,21212.5,15888.0,25579.5,16200.0,282.307090,0.094219,0.066121,0.040456,1623.890342,141.569927,174.880498,124.914642
4,E09000005,Brent,11786.0,15204.0,18687.0,23514.0,10075.0,330.407602,0.085015,0.047564,0.028138,606.143442,635.856356,368.440131,332.784635

In [184]:
col_names = ['income_rank', 'employment_rank', 'education_rank', 
             'health_rank', 'living_env_rank']
london_deprivation = pd.melt(london_combined_agg, id_vars=['code', 'name', 'covid_deaths'], 
                        value_vars=col_names, var_name = 'rank_description', value_name='rank_value')

london_deprivation.head()

        code                  name  covid_deaths rank_description  rank_value
0  E09000001        City of London    112.781955      income_rank     30837.5
1  E09000002  Barking and Dagenham    278.625197      income_rank      6888.5
2  E09000003                Barnet    284.926377      income_rank     17032.0
3  E09000004                Bexley    282.307090      income_rank     18572.0
4  E09000005                 Brent    330.407602      income_rank     11786.0

In [189]:
col_names = ['60s_proportion', '70s_proportion',
             '80s_proportion']
london_demographic = pd.melt(london_combined_agg, id_vars=['code', 'name', 'covid_deaths'], 
                        value_vars=col_names, var_name = 'description', value_name='value')

london_demographic.head()

        code                  name  covid_deaths     description     value
0  E09000001        City of London    112.781955  60s_proportion  0.104699
1  E09000002  Barking and Dagenham    278.625197  60s_proportion  0.065076
2  E09000003                Barnet    284.926377  60s_proportion  0.084028
3  E09000004                Bexley    282.307090  60s_proportion  0.094219
4  E09000005                 Brent    330.407602  60s_proportion  0.085015

In [190]:
col_names = ['White', 'Asian', 'Black']
london_ethnic = pd.melt(london_combined_agg, id_vars=['code', 'name', 'covid_deaths'], 
                        value_vars=col_names, var_name = 'description', value_name='value')

london_ethnic.head()

        code                  name  covid_deaths description     value
0  E09000001        City of London    112.781955       White  1.691729
1  E09000002  Barking and Dagenham    278.625197       White  1.029496
2  E09000003                Barnet    284.926377       White  1.271993
3  E09000004                Bexley    282.307090       White  1.623890
4  E09000005                 Brent    330.407602       White  0.606143

In [191]:
alt.Chart(london_deprivation).mark_point().encode(
    x='covid_deaths:Q',
    y='rank_value:Q', 
    tooltip = ['name']
).properties(
    width=180,
    height=180
).facet(
    column='rank_description:N'
).interactive()

alt.FacetChart(...)

In [192]:
alt.Chart(london_demographic).mark_point().encode(
    x='covid_deaths:Q',
    y='value:Q', 
    tooltip = ['name']
).properties(
    width=180,
    height=180
).facet(
    column='description:N'
).interactive()

alt.FacetChart(...)

In [193]:
alt.Chart(london_ethnic).mark_point().encode(
    x='covid_deaths:Q',
    y='value:Q', 
    tooltip = ['name']
).properties(
    width=180,
    height=180
).facet(
    column='description:N'
).interactive()

alt.FacetChart(...)

In [ ]:
# I now want to turn into grids of 100 x 100 (but this time I want to do versus the weekly death data) so I can create a facet grid heatmap